### ISSUE TITLE
Unexpected Token member

### ISSUE THREAD

**Issue by mcormier** [deepsky/SQL-Code-Assistant-#10]
The word member gets highlighted as an error.  I'm working with a database that has a table called "member" so I've got errors all over the place.

Steps to reproduce:
1. Create a test.sql file
2.  Put the line "select \* from member" in it.

![member](https://f.cloud.github.com/assets/39216/2420396/68b9e48e-ab70-11e3-9275-3e53bb1273ba.png)

**Comment by deepsky** [comment]
Thanks Matthieu for reporting!
Going to fix it in few days, one question, what plug-in version do you use?
Best regards,
Serhiy

**Comment by deepsky** [comment]
Fixed in 3be3da0876d3609a2b1eca2da9c2279db0ff6f04

**Comment by deepsky** [comment]
Fixed in 1.5.9.X version

**Comment by mcormier** [comment]
Super-mega-awesome.
