### ISSUE TITLE
RESULT_CACHE support

### ISSUE THREAD

**Issue by mcormier** [deepsky/SQL-Code-Assistant-#11]
RESULT_CACHE was introduced by Oracle in version 11.2

It genenates an unexpected token error in SQL-Code-Assistant.

Example usage:

```
FUNCTION some_function(some_code IN CHAR) return INT RESULT_CACHE;
```

Reference link:
http://stackoverflow.com/questions/2290809/how-to-enable-function-result-cache

**Comment by deepsky** [comment]
Thanks! Going to fix and update plug-in in a few days.

**Comment by deepsky** [comment]
Fixed in 3be3da0876d3609a2b1eca2da9c2279db0ff6f04

**Comment by deepsky** [comment]
Fixed in 1.5.9.X version

**Comment by mcormier** [comment]
Sweet, upgraded this morning, works like a charm.

**Comment by deepsky** [comment]
Thanks :) I will appreciate if you rate the plug-in.

**Comment by mcormier** [comment]
Done: http://plugins.jetbrains.com/plugin/4486?pr=phpStorm

**Comment by deepsky** [comment]
Thanks, Matthieu :)
