### ISSUE TITLE
Database Connection  Passwords

### ISSUE THREAD

**Issue by gmenessy** [deepsky/SQL-Code-Assistant-#6]
The character # is not accepted in passwords. But Oracle accepts these characters

Example:

aa#jj#d

**Comment by deepsky** [comment]
Hi Menessy, thanks for reporting  of the issue! I'll update the plugin
and let you know, hoping to have it ready on the next week.

Regards,
Serhiy

**Comment by deepsky** [comment]
Fixed in ba4c854
Release 1.4.9.12/13
