### ISSUE TITLE
Source code formatting error

### ISSUE THREAD

**Issue by gmenessy** [deepsky/SQL-Code-Assistant-#7]
From:
  l_stmt :=                                  l_stmt || '  WHERE  hase=''01''  AND ';

to.
  l_stmt := l_stmt || '  WHERE  hase=' '01' '  AND ';

The error is the space between the 2 inverted commas

**Comment by serge2004-ua** [comment]
Good catch Manessy :) Hoping to have the plugin patched and uploaded in the repository on the next week.
Thanks!
Serhiy

**Comment by deepsky** [comment]
Fixed in 02b353f 
Release 1.4.9.12/13
